// Seed data: ingredients + recipes. All local, no backend.
// Ingredient helper: [id, name, category, aliases?, isStaple?]
const I = (id, name, category, aliases = [], isStaple = false) => ({
  id, name, category, aliases, isStaple,
});

export const CATEGORIES = [
  { id: 'protein', label: 'Proteins' },
  { id: 'veg',     label: 'Veg & Fruit' },
  { id: 'dairy',   label: 'Dairy & Eggs' },
  { id: 'grain',   label: 'Grains & Carbs' },
  { id: 'pantry',  label: 'Pantry' },
  { id: 'spice',   label: 'Spices' },
  { id: 'other',   label: 'Other' },
];

export const INGREDIENTS = [
  // Proteins
  I('chicken-breast', 'Chicken breast', 'protein', ['chicken']),
  I('chicken-thigh',  'Chicken thighs', 'protein', ['chicken thigh']),
  I('ground-beef',    'Ground beef', 'protein', ['minced beef', 'beef mince']),
  I('ground-pork',    'Ground pork', 'protein', ['minced pork', 'pork mince']),
  I('ground-turkey',  'Ground turkey', 'protein', ['minced turkey']),
  I('steak',          'Steak', 'protein', ['beef steak', 'sirloin']),
  I('pork-chop',      'Pork chops', 'protein', ['pork loin']),
  I('bacon',          'Bacon', 'protein', ['streaky bacon']),
  I('ham',            'Ham', 'protein', ['deli ham']),
  I('sausage',        'Sausages', 'protein', ['sausages', 'bratwurst']),
  I('salmon',         'Salmon', 'protein', ['salmon fillet']),
  I('white-fish',     'White fish', 'protein', ['cod', 'tilapia', 'sea bass', 'dory']),
  I('shrimp',         'Shrimp', 'protein', ['prawns', 'prawn']),
  I('canned-tuna',    'Canned tuna', 'protein', ['tuna', 'tinned tuna']),
  I('tofu',           'Tofu', 'protein', ['bean curd']),

  // Veg & fruit
  I('onion',          'Onion', 'veg', ['red onion', 'yellow onion', 'shallot']),
  I('garlic',         'Garlic', 'veg', ['garlic cloves']),
  I('ginger',         'Ginger', 'veg', ['fresh ginger']),
  I('scallion',       'Scallions', 'veg', ['green onion', 'spring onion', 'green onions']),
  I('tomato',         'Tomatoes', 'veg', ['tomato']),
  I('cherry-tomatoes','Cherry tomatoes', 'veg', ['grape tomatoes']),
  I('bell-pepper',    'Bell pepper', 'veg', ['capsicum', 'red pepper', 'green pepper']),
  I('carrot',         'Carrots', 'veg', ['carrot']),
  I('celery',         'Celery', 'veg', []),
  I('broccoli',       'Broccoli', 'veg', ['broccolini']),
  I('cauliflower',    'Cauliflower', 'veg', []),
  I('spinach',        'Spinach', 'veg', ['baby spinach']),
  I('kale',           'Kale', 'veg', []),
  I('lettuce',        'Lettuce', 'veg', ['romaine', 'iceberg', 'salad greens']),
  I('cucumber',       'Cucumber', 'veg', []),
  I('zucchini',       'Zucchini', 'veg', ['courgette']),
  I('eggplant',       'Eggplant', 'veg', ['aubergine', 'brinjal']),
  I('mushrooms',      'Mushrooms', 'veg', ['button mushrooms', 'cremini', 'shiitake']),
  I('potato',         'Potatoes', 'veg', ['potato', 'russet']),
  I('sweet-potato',   'Sweet potato', 'veg', ['yam']),
  I('corn',           'Corn', 'veg', ['sweetcorn', 'corn kernels', 'canned corn']),
  I('frozen-peas',    'Peas', 'veg', ['peas', 'green peas']),
  I('green-beans',    'Green beans', 'veg', ['string beans']),
  I('cabbage',        'Cabbage', 'veg', ['napa cabbage', 'savoy']),
  I('bok-choy',       'Bok choy', 'veg', ['pak choi', 'pok choy']),
  I('avocado',        'Avocado', 'veg', []),
  I('lemon',          'Lemon', 'veg', ['lemons']),
  I('lime',           'Lime', 'veg', ['limes']),
  I('fresh-chili',    'Fresh chili', 'veg', ['chili', 'chilli', 'jalapeno', 'bird\'s eye']),
  I('cilantro',       'Cilantro', 'veg', ['coriander', 'fresh coriander']),
  I('parsley',        'Parsley', 'veg', ['flat-leaf parsley']),
  I('basil',          'Basil', 'veg', ['fresh basil', 'thai basil']),
  I('banana',         'Bananas', 'veg', ['banana']),
  I('apple',          'Apples', 'veg', ['apple']),
  I('berries',        'Berries', 'veg', ['strawberries', 'blueberries', 'raspberries']),

  // Dairy & eggs
  I('eggs',           'Eggs', 'dairy', ['egg']),
  I('milk',           'Milk', 'dairy', ['whole milk', 'oat milk']),
  I('butter',         'Butter', 'dairy', ['salted butter', 'unsalted butter']),
  I('heavy-cream',    'Heavy cream', 'dairy', ['whipping cream', 'double cream', 'cream']),
  I('sour-cream',     'Sour cream', 'dairy', ['creme fraiche']),
  I('greek-yogurt',   'Yogurt', 'dairy', ['greek yogurt', 'yoghurt', 'plain yogurt']),
  I('cream-cheese',   'Cream cheese', 'dairy', []),
  I('cheddar',        'Cheddar', 'dairy', ['cheese', 'cheese slices', 'shredded cheese']),
  I('mozzarella',     'Mozzarella', 'dairy', ['fresh mozzarella']),
  I('parmesan',       'Parmesan', 'dairy', ['parmigiano', 'grana padano', 'pecorino']),
  I('feta',           'Feta', 'dairy', ['feta cheese']),

  // Grains & carbs
  I('rice',           'Rice', 'grain', ['white rice', 'jasmine rice', 'basmati']),
  I('pasta',          'Pasta', 'grain', ['spaghetti', 'penne', 'fusilli', 'noodles', 'macaroni']),
  I('instant-noodles','Instant noodles', 'grain', ['ramen', 'instant ramen', 'maggi']),
  I('rice-noodles',   'Rice noodles', 'grain', ['pad thai noodles', 'vermicelli']),
  I('bread',          'Bread', 'grain', ['toast', 'sandwich bread', 'sourdough', 'baguette']),
  I('tortillas',      'Tortillas', 'grain', ['wraps', 'flour tortillas', 'corn tortillas']),
  I('flour',          'Flour', 'grain', ['all-purpose flour', 'plain flour']),
  I('oats',           'Oats', 'grain', ['rolled oats', 'oatmeal']),
  I('quinoa',         'Quinoa', 'grain', []),
  I('couscous',       'Couscous', 'grain', []),
  I('breadcrumbs',    'Breadcrumbs', 'grain', ['panko']),
  I('granola',        'Granola', 'grain', ['muesli']),

  // Pantry
  I('olive-oil',      'Olive oil', 'pantry', ['extra virgin olive oil'], true),
  I('neutral-oil',    'Cooking oil', 'pantry', ['vegetable oil', 'canola oil', 'sunflower oil'], true),
  I('sugar',          'Sugar', 'pantry', ['brown sugar', 'white sugar'], true),
  I('soy-sauce',      'Soy sauce', 'pantry', ['light soy', 'dark soy', 'tamari']),
  I('oyster-sauce',   'Oyster sauce', 'pantry', []),
  I('fish-sauce',     'Fish sauce', 'pantry', ['nam pla']),
  I('sesame-oil',     'Sesame oil', 'pantry', ['toasted sesame oil']),
  I('rice-vinegar',   'Rice vinegar', 'pantry', ['rice wine vinegar', 'mirin']),
  I('vinegar',        'Vinegar', 'pantry', ['white vinegar', 'apple cider vinegar', 'balsamic']),
  I('sriracha',       'Hot sauce', 'pantry', ['sriracha', 'tabasco', 'sambal']),
  I('ketchup',        'Ketchup', 'pantry', ['tomato ketchup']),
  I('mayo',           'Mayonnaise', 'pantry', ['mayo', 'kewpie']),
  I('mustard',        'Mustard', 'pantry', ['dijon', 'whole grain mustard']),
  I('honey',          'Honey', 'pantry', []),
  I('maple-syrup',    'Maple syrup', 'pantry', ['pancake syrup']),
  I('peanut-butter',  'Peanut butter', 'pantry', ['pb']),
  I('canned-tomatoes','Canned tomatoes', 'pantry', ['crushed tomatoes', 'diced tomatoes', 'passata']),
  I('tomato-paste',   'Tomato paste', 'pantry', ['tomato puree']),
  I('coconut-milk',   'Coconut milk', 'pantry', ['coconut cream']),
  I('stock',          'Stock', 'pantry', ['chicken stock', 'chicken broth', 'vegetable stock', 'broth', 'bouillon']),
  I('chickpeas',      'Chickpeas', 'pantry', ['canned chickpeas', 'garbanzo beans']),
  I('black-beans',    'Black beans', 'pantry', ['canned black beans']),
  I('lentils',        'Lentils', 'pantry', ['red lentils', 'green lentils']),
  I('olives',         'Olives', 'pantry', ['kalamata', 'black olives', 'green olives']),
  I('curry-paste',    'Curry paste', 'pantry', ['thai curry paste', 'red curry paste', 'green curry paste']),
  I('gochujang',      'Gochujang', 'pantry', ['korean chili paste']),
  I('miso',           'Miso paste', 'pantry', ['miso', 'white miso']),
  I('sesame-seeds',   'Sesame seeds', 'pantry', ['toasted sesame']),
  I('chocolate-chips','Chocolate chips', 'pantry', ['choc chips']),
  I('baking-powder',  'Baking powder', 'pantry', ['baking soda']),

  // Spices
  I('salt',           'Salt', 'spice', ['sea salt', 'kosher salt'], true),
  I('black-pepper',   'Black pepper', 'spice', ['pepper'], true),
  I('chili-flakes',   'Chili flakes', 'spice', ['red pepper flakes', 'cayenne', 'chilli flakes']),
  I('paprika',        'Paprika', 'spice', ['smoked paprika']),
  I('cumin',          'Cumin', 'spice', ['ground cumin']),
  I('turmeric',       'Turmeric', 'spice', []),
  I('curry-powder',   'Curry powder', 'spice', ['garam masala']),
  I('oregano',        'Oregano', 'spice', ['dried oregano']),
  I('thyme',          'Thyme', 'spice', ['dried thyme']),
  I('rosemary',       'Rosemary', 'spice', []),
  I('cinnamon',       'Cinnamon', 'spice', ['ground cinnamon']),
  I('garlic-powder',  'Garlic powder', 'spice', ['onion powder']),
  I('five-spice',     'Five spice', 'spice', ['chinese five spice']),

  // Other
  I('kimchi',         'Kimchi', 'other', []),
  I('dark-chocolate', 'Dark chocolate', 'other', ['chocolate bar']),
  I('tortilla-chips', 'Tortilla chips', 'other', ['corn chips', 'nachos']),
];

// ---- Freshness seed -----------------------------------------------------
// Default shelf life in days per ingredient. null = staple / non-perishable
// (canned, dried, frozen, condiments): no expiry tracking, no expiry UI.
// Unlisted ingredients fall back to their category default below.
const CATEGORY_SHELF_LIFE = {
  protein: 3, veg: 7, dairy: 14, grain: null, pantry: null, spice: null, other: null,
};

const SHELF_LIFE_OVERRIDES = {
  // proteins: fish faster than meat; cured lasts longer; canned is staple
  salmon: 2, 'white-fish': 2, shrimp: 2,
  bacon: 14, ham: 7, sausage: 7, tofu: 7, 'canned-tuna': null,
  // veg & fruit: leafy/berries fast, roots and citrus slow, frozen is staple
  spinach: 4, kale: 5, lettuce: 5, basil: 4, cilantro: 4, parsley: 5,
  scallion: 6, berries: 3, mushrooms: 5, avocado: 4, banana: 5,
  'bok-choy': 5, corn: 5, 'cherry-tomatoes': 5, tomato: 6,
  'bell-pepper': 10, cauliflower: 10, 'fresh-chili': 10,
  cabbage: 14, celery: 14,
  ginger: 21, 'sweet-potato': 21, carrot: 21, lemon: 21, lime: 21, apple: 21,
  onion: 30, garlic: 30, potato: 30,
  'frozen-peas': null,
  // dairy & eggs
  milk: 7, 'heavy-cream': 7, mozzarella: 7,
  eggs: 21, cheddar: 30, butter: 60, parmesan: 60,
  // grains: fresh bread is the exception
  bread: 5, tortillas: 14,
  // other
  kimchi: 30,
};

const tierFor = (days) => {
  if (days == null) return 'staple';
  if (days <= 4) return 'highly_perishable';
  if (days <= 10) return 'perishable';
  return 'long_life';
};

for (const ing of INGREDIENTS) {
  const days = ing.isStaple ? null
    : (SHELF_LIFE_OVERRIDES[ing.id] !== undefined
        ? SHELF_LIFE_OVERRIDES[ing.id]
        : CATEGORY_SHELF_LIFE[ing.category]);
  ing.defaultShelfLifeDays = days;
  ing.freshnessTier = tierFor(days);
}

// Recipe helper. Staples (salt, pepper, oil, sugar) are never listed in
// required: with assumeStaples on they are auto-owned, so listing them
// would only pad the coverage math.
const R = (id, name, timeMinutes, difficulty, servings, required, optional, steps, tags = []) => ({
  id, name, timeMinutes, difficulty, servings,
  requiredIngredientIds: required,
  optionalIngredientIds: optional,
  steps, tags,
});

export const RECIPES = [
  R('garlic-butter-pasta', 'Garlic butter pasta', 15, 'easy', 2,
    ['pasta', 'butter', 'garlic', 'parmesan'], ['parsley', 'chili-flakes', 'lemon'],
    ['Cook the pasta in well-salted water until just shy of tender. Save a mug of pasta water.',
     'Melt the butter over medium-low heat and cook sliced garlic until fragrant, about 1 minute.',
     'Toss in the drained pasta with a splash of pasta water until glossy.',
     'Turn off the heat, shower with parmesan, and toss again. Finish with parsley or chili flakes if you have them.'],
    ['vegetarian', 'quick']),

  R('aglio-e-olio', 'Spaghetti aglio e olio', 15, 'easy', 2,
    ['pasta', 'garlic', 'chili-flakes'], ['parsley', 'parmesan', 'lemon'],
    ['Boil the pasta in salty water. Keep a mug of the cooking water.',
     'Gently warm plenty of olive oil with thin-sliced garlic and chili flakes until the garlic turns pale gold.',
     'Add the pasta and a big splash of pasta water. Toss hard until the sauce clings.',
     'Finish with parsley, parmesan, or a squeeze of lemon.'],
    ['vegan', 'quick']),

  R('weeknight-tomato-pasta', 'Weeknight tomato pasta', 25, 'easy', 3,
    ['pasta', 'canned-tomatoes', 'garlic', 'onion'], ['basil', 'parmesan', 'butter', 'chili-flakes'],
    ['Soften diced onion in olive oil, then add sliced garlic for a minute.',
     'Pour in the canned tomatoes, season, and simmer 15 minutes while the pasta cooks.',
     'A knob of butter at the end makes the sauce silky.',
     'Toss the pasta through the sauce and top with basil and parmesan.'],
    ['vegetarian']),

  R('creamy-mushroom-pasta', 'Creamy mushroom pasta', 25, 'easy', 2,
    ['pasta', 'mushrooms', 'garlic', 'heavy-cream'], ['parmesan', 'thyme', 'spinach', 'onion'],
    ['Sear sliced mushrooms in a hot pan until browned. Do not crowd them.',
     'Lower the heat, add garlic and thyme, then pour in the cream.',
     'Simmer 2 minutes, then toss with cooked pasta and a splash of pasta water.',
     'Stir in spinach to wilt and finish with parmesan.'],
    ['vegetarian']),

  R('tuna-lemon-pasta', 'Tuna and lemon pasta', 20, 'easy', 2,
    ['pasta', 'canned-tuna', 'garlic', 'lemon'], ['olives', 'parsley', 'chili-flakes'],
    ['Cook the pasta. Meanwhile warm olive oil with garlic and chili flakes.',
     'Add drained tuna and olives, breaking the tuna into big flakes.',
     'Toss with the pasta, lemon zest, and a good squeeze of juice.',
     'Loosen with pasta water and finish with parsley.'],
    ['quick']),

  R('bacon-egg-pasta', 'Bacon and egg pasta', 20, 'medium', 2,
    ['pasta', 'bacon', 'eggs', 'parmesan'], [],
    ['Whisk eggs with a big handful of grated parmesan and lots of black pepper.',
     'Crisp chopped bacon in a wide pan, then turn off the heat.',
     'Add hot drained pasta to the bacon, wait 30 seconds, then pour in the egg mix.',
     'Toss fast, adding pasta water until the sauce is glossy, never scrambled.'],
    []),

  R('stovetop-mac', 'Stovetop mac and cheese', 20, 'easy', 2,
    ['pasta', 'milk', 'butter', 'cheddar'], ['flour', 'mustard'],
    ['Cook the pasta 1 minute short of the packet time.',
     'Melt butter, stir in a spoon of flour if you have it, then whisk in milk until smooth.',
     'Off the heat, melt in handfuls of cheddar and a dab of mustard.',
     'Fold in the pasta and season generously.'],
    ['vegetarian', 'comfort']),

  R('egg-fried-rice', 'Egg fried rice', 15, 'easy', 2,
    ['rice', 'eggs', 'scallion', 'soy-sauce'], ['frozen-peas', 'carrot', 'garlic', 'sesame-oil'],
    ['Use cold leftover rice if you can. Break up the clumps.',
     'Scramble the eggs in a hot oiled pan and set aside.',
     'Stir-fry the rice hard until it smells toasty, then add peas or carrot.',
     'Return the eggs, season with soy sauce, and finish with scallions and sesame oil.'],
    ['vegetarian', 'quick']),

  R('kimchi-fried-rice', 'Kimchi fried rice', 20, 'easy', 2,
    ['rice', 'kimchi', 'eggs'], ['scallion', 'gochujang', 'sesame-oil', 'bacon', 'soy-sauce'],
    ['Crisp chopped bacon if using, then fry chopped kimchi in the fat for 2 minutes.',
     'Add cold rice and a spoon of gochujang. Stir-fry until everything is stained red.',
     'Season with soy sauce and sesame oil.',
     'Top each bowl with a fried egg and scallions.'],
    ['quick', 'spicy']),

  R('chicken-fried-rice', 'Chicken fried rice', 25, 'easy', 2,
    ['rice', 'chicken-breast', 'eggs', 'soy-sauce'], ['frozen-peas', 'carrot', 'scallion', 'garlic', 'sesame-oil'],
    ['Dice the chicken small and stir-fry in a hot pan until just cooked. Set aside.',
     'Scramble the eggs, then add cold rice and break it up.',
     'Return the chicken with peas and carrot, and season with soy sauce.',
     'Finish with scallions and a drop of sesame oil.'],
    []),

  R('one-pot-chicken-rice', 'One-pot chicken and rice', 40, 'medium', 4,
    ['chicken-thigh', 'rice', 'onion', 'garlic', 'stock'], ['thyme', 'lemon', 'frozen-peas', 'paprika'],
    ['Season the thighs and brown them skin-side down in a lidded pot. Set aside.',
     'Soften the onion and garlic in the chicken fat.',
     'Stir in the rice, pour over hot stock, and nestle the chicken on top.',
     'Cover and cook on low 20 minutes. Rest 5, then fluff with peas and lemon.'],
    ['one-pan']),

  R('honey-soy-chicken', 'Honey soy chicken', 25, 'easy', 2,
    ['chicken-thigh', 'soy-sauce', 'honey', 'garlic'], ['ginger', 'scallion', 'sesame-seeds', 'rice'],
    ['Mix soy sauce, honey, grated garlic, and ginger into a glaze.',
     'Sear the chicken in a hot pan until golden on both sides.',
     'Pour in the glaze and let it bubble, turning the chicken to coat.',
     'Serve over rice, scattered with scallions and sesame seeds.'],
    ['quick']),

  R('chicken-stir-fry', 'Chicken and pepper stir-fry', 20, 'easy', 2,
    ['chicken-breast', 'bell-pepper', 'broccoli', 'soy-sauce', 'garlic'], ['ginger', 'oyster-sauce', 'rice', 'sesame-oil'],
    ['Slice the chicken thin and toss with a spoon of soy sauce.',
     'Stir-fry the chicken in a screaming hot pan until just cooked. Set aside.',
     'Stir-fry broccoli and peppers 2 minutes, then add garlic and ginger.',
     'Return the chicken with soy and oyster sauce. Serve over rice.'],
    ['quick']),

  R('beef-and-broccoli', 'Beef and broccoli', 25, 'medium', 2,
    ['steak', 'broccoli', 'soy-sauce', 'garlic', 'ginger'], ['oyster-sauce', 'rice', 'sesame-oil', 'scallion'],
    ['Slice the steak thin against the grain and toss with soy sauce.',
     'Blanch or steam the broccoli 2 minutes so it stays snappy.',
     'Sear the beef hard in batches, then add garlic and ginger.',
     'Return the broccoli with soy and oyster sauce, toss, and serve over rice.'],
    []),

  R('beef-tacos', 'Ground beef tacos', 25, 'easy', 3,
    ['ground-beef', 'tortillas', 'onion', 'cumin', 'paprika'], ['cheddar', 'lettuce', 'tomato', 'sour-cream', 'lime', 'garlic'],
    ['Brown the beef hard in a dry pan, breaking it into crumbles.',
     'Add diced onion, cumin, paprika, and a splash of water. Simmer 5 minutes.',
     'Warm the tortillas in a dry pan.',
     'Build tacos with cheese, lettuce, tomato, and a squeeze of lime.'],
    []),

  R('cheese-quesadillas', 'Crispy quesadillas', 15, 'easy', 2,
    ['tortillas', 'cheddar'], ['black-beans', 'scallion', 'sour-cream', 'sriracha', 'avocado'],
    ['Scatter cheese over half of each tortilla, plus beans or scallions if you like.',
     'Fold and cook in a dry pan over medium heat until deeply golden, about 3 minutes a side.',
     'Rest 1 minute so the cheese sets, then slice.',
     'Dip in sour cream and hot sauce.'],
    ['vegetarian', 'quick']),

  R('burrito-bowl', 'Burrito bowl', 30, 'easy', 2,
    ['rice', 'black-beans', 'corn', 'lime'], ['avocado', 'cilantro', 'cheddar', 'sour-cream', 'chicken-breast', 'sriracha'],
    ['Cook the rice and fold in lime juice and chopped cilantro.',
     'Warm the beans with a pinch of cumin if you have it. Char the corn in a dry pan.',
     'Grill or pan-fry chicken if using and slice it.',
     'Build bowls: rice, beans, corn, then avocado, cheese, and sour cream on top.'],
    []),

  R('weeknight-chili', 'Weeknight chili', 45, 'medium', 4,
    ['ground-beef', 'canned-tomatoes', 'black-beans', 'onion', 'cumin'], ['garlic', 'chili-flakes', 'cheddar', 'sour-cream', 'tomato-paste'],
    ['Brown the beef hard, then push it aside and soften the onion.',
     'Add garlic, cumin, chili flakes, and tomato paste. Cook 1 minute.',
     'Pour in tomatoes and beans, then simmer 25 minutes until thick.',
     'Serve with cheddar and sour cream on top.'],
    ['comfort']),

  R('simple-bolognese', 'Simple bolognese', 60, 'medium', 4,
    ['ground-beef', 'canned-tomatoes', 'onion', 'garlic', 'pasta'], ['carrot', 'celery', 'milk', 'parmesan', 'oregano', 'tomato-paste'],
    ['Soften finely diced onion, carrot, and celery in olive oil.',
     'Add the beef and brown it properly, then stir in garlic and tomato paste.',
     'Pour in the tomatoes and a splash of milk. Simmer gently 40 minutes.',
     'Toss with pasta and plenty of parmesan.'],
    ['comfort']),

  R('cheesy-omelette', 'Cheesy omelette', 10, 'easy', 1,
    ['eggs', 'butter', 'cheddar'], ['scallion', 'mushrooms', 'ham', 'tomato'],
    ['Whisk 3 eggs with a pinch of salt until smooth.',
     'Melt butter over medium heat and pour in the eggs, stirring gently as they set.',
     'When almost set, add cheese and any fillings down the middle.',
     'Fold, slide onto a plate, and eat immediately.'],
    ['vegetarian', 'quick', 'breakfast']),

  R('scrambled-egg-toast', 'Soft scrambled eggs on toast', 10, 'easy', 1,
    ['eggs', 'bread', 'butter'], ['scallion', 'cheddar', 'sriracha'],
    ['Toast the bread and butter it while hot.',
     'Whisk the eggs, then cook in butter over LOW heat, stirring constantly.',
     'Pull the pan off the heat while the eggs still look slightly wet.',
     'Pile onto the toast with scallions or hot sauce.'],
    ['vegetarian', 'quick', 'breakfast']),

  R('shakshuka', 'Shakshuka', 30, 'medium', 2,
    ['eggs', 'canned-tomatoes', 'onion', 'bell-pepper', 'cumin'], ['garlic', 'feta', 'parsley', 'bread', 'paprika', 'chili-flakes'],
    ['Soften sliced onion and pepper in olive oil, about 8 minutes.',
     'Add garlic, cumin, and paprika, then the canned tomatoes. Simmer 10 minutes.',
     'Make wells and crack in the eggs. Cover until the whites set.',
     'Crumble over feta and scoop up with bread.'],
    ['vegetarian', 'one-pan', 'breakfast']),

  R('egg-drop-soup', 'Egg drop soup', 15, 'easy', 2,
    ['stock', 'eggs', 'scallion'], ['ginger', 'sesame-oil', 'corn'],
    ['Bring the stock to a gentle simmer with a few ginger slices.',
     'Whisk the eggs in a cup with a fork.',
     'Swirl the soup and pour the egg in a thin stream to make ribbons.',
     'Finish with scallions and a drop of sesame oil.'],
    ['quick', 'soup']),

  R('fluffy-pancakes', 'Fluffy pancakes', 25, 'easy', 3,
    ['flour', 'eggs', 'milk', 'baking-powder'], ['butter', 'maple-syrup', 'berries', 'banana'],
    ['Whisk flour, baking powder, a spoon of sugar, and a pinch of salt.',
     'Whisk in milk and eggs until just combined. Lumps are fine.',
     'Cook ladles of batter in a buttered pan until bubbles pop, then flip.',
     'Stack high with syrup and fruit.'],
    ['vegetarian', 'breakfast']),

  R('french-toast', 'French toast', 15, 'easy', 2,
    ['bread', 'eggs', 'milk', 'cinnamon'], ['butter', 'maple-syrup', 'berries'],
    ['Whisk eggs, milk, cinnamon, and a spoon of sugar in a shallow dish.',
     'Soak thick bread slices 20 seconds a side.',
     'Fry in butter over medium heat until golden on both sides.',
     'Serve with syrup and berries.'],
    ['vegetarian', 'quick', 'breakfast']),

  R('banana-oat-pancakes', 'Banana oat pancakes', 15, 'easy', 2,
    ['banana', 'oats', 'eggs'], ['cinnamon', 'peanut-butter', 'maple-syrup'],
    ['Blend or mash bananas, oats, eggs, and cinnamon into a thick batter.',
     'Rest the batter 5 minutes so the oats soften.',
     'Cook small pancakes over medium-low heat, flipping once.',
     'Top with peanut butter or syrup.'],
    ['vegetarian', 'quick', 'breakfast']),

  R('overnight-oats', 'Overnight oats', 5, 'easy', 1,
    ['oats', 'milk', 'honey'], ['greek-yogurt', 'berries', 'banana', 'peanut-butter', 'cinnamon'],
    ['Stir oats, milk, honey, and a pinch of salt in a jar.',
     'Add a spoon of yogurt or peanut butter for creaminess.',
     'Refrigerate overnight, or at least 4 hours.',
     'Top with fruit before eating.'],
    ['vegetarian', 'no-cook', 'breakfast']),

  R('yogurt-parfait', 'Yogurt parfait', 5, 'easy', 1,
    ['greek-yogurt', 'granola', 'berries'], ['honey', 'banana'],
    ['Layer yogurt, granola, and berries in a glass.',
     'Repeat the layers until you run out.',
     'Drizzle honey over the top.',
     'Eat immediately while the granola is still crunchy.'],
    ['vegetarian', 'no-cook', 'quick', 'breakfast']),

  R('grilled-cheese', 'Grilled cheese', 10, 'easy', 1,
    ['bread', 'butter', 'cheddar'], ['ham', 'tomato', 'mustard'],
    ['Butter the OUTSIDE of two bread slices.',
     'Fill with a generous layer of cheddar, plus ham or mustard if you like.',
     'Cook in a pan over medium-low heat, pressing gently, until deep gold on both sides.',
     'Rest 1 minute, then slice diagonally. That part is mandatory.'],
    ['vegetarian', 'quick', 'comfort']),

  R('tomato-soup', 'Tomato soup', 30, 'easy', 3,
    ['canned-tomatoes', 'onion', 'garlic', 'stock'], ['heavy-cream', 'butter', 'basil', 'bread'],
    ['Soften the onion in butter or olive oil, then add garlic.',
     'Pour in tomatoes and stock. Simmer 15 minutes.',
     'Blend until smooth and finish with a swirl of cream.',
     'Serve with grilled cheese or crusty bread for dunking.'],
    ['vegetarian', 'soup', 'comfort']),

  R('avocado-toast', 'Avocado toast', 10, 'easy', 1,
    ['bread', 'avocado', 'lemon'], ['eggs', 'chili-flakes', 'feta'],
    ['Toast the bread until properly crisp.',
     'Smash the avocado with lemon juice, salt, and pepper.',
     'Spread thick and top with chili flakes or crumbled feta.',
     'Add a fried egg on top to make it a meal.'],
    ['vegetarian', 'quick', 'breakfast']),

  R('blt', 'The BLT', 15, 'easy', 1,
    ['bread', 'bacon', 'lettuce', 'tomato', 'mayo'], ['avocado'],
    ['Cook the bacon until properly crisp. Drain on paper.',
     'Toast the bread and spread both slices with mayo.',
     'Layer lettuce, thick tomato slices seasoned with salt, then bacon.',
     'Cut in half and admire the cross-section before eating.'],
    ['quick']),

  R('tuna-melt', 'Tuna melt', 15, 'easy', 1,
    ['bread', 'canned-tuna', 'mayo', 'cheddar'], ['onion', 'celery', 'mustard'],
    ['Mix drained tuna with mayo, diced celery or onion, and pepper.',
     'Pile onto bread and blanket with cheddar.',
     'Broil or pan-toast until the cheese bubbles and browns.',
     'Eat hot with pickles if you have them.'],
    ['quick']),

  R('chicken-noodle-soup', 'Chicken noodle soup', 45, 'medium', 4,
    ['chicken-breast', 'stock', 'carrot', 'celery', 'pasta'], ['onion', 'garlic', 'thyme', 'parsley'],
    ['Soften diced onion, carrot, and celery in a soup pot.',
     'Add stock and the chicken. Simmer gently 15 minutes.',
     'Lift out the chicken, shred it, and return it with the pasta.',
     'Cook until the pasta is tender. Finish with parsley.'],
    ['soup', 'comfort']),

  R('upgraded-ramen', 'Upgraded instant ramen', 12, 'easy', 1,
    ['instant-noodles', 'eggs', 'scallion'], ['butter', 'kimchi', 'sesame-oil', 'cheddar', 'sriracha'],
    ['Cook the noodles 1 minute less than the packet says.',
     'Use half the seasoning packet, plus a knob of butter for a richer broth.',
     'Slide in an egg for the last 2 minutes, or top with a soft-boiled one.',
     'Finish with scallions, kimchi, and a drop of sesame oil.'],
    ['quick', 'comfort']),

  R('peanut-noodles', 'Peanut noodles', 15, 'easy', 2,
    ['pasta', 'peanut-butter', 'soy-sauce', 'garlic'], ['lime', 'sriracha', 'scallion', 'cucumber', 'sesame-seeds', 'honey'],
    ['Whisk peanut butter, soy sauce, grated garlic, and warm water into a pourable sauce.',
     'Add lime juice, honey, and sriracha to balance it. Taste as you go.',
     'Toss with hot cooked noodles.',
     'Top with cucumber matchsticks, scallions, and sesame seeds. Great cold too.'],
    ['vegetarian', 'quick']),

  R('pad-thai-ish', 'Pad-thai-ish noodles', 25, 'medium', 2,
    ['rice-noodles', 'eggs', 'fish-sauce', 'lime'], ['shrimp', 'tofu', 'scallion', 'peanut-butter', 'garlic', 'chili-flakes'],
    ['Soak the rice noodles in hot water until bendy but not soft.',
     'Stir together fish sauce, lime juice, and sugar for the sauce.',
     'Stir-fry shrimp or tofu, push aside, and scramble the eggs.',
     'Add noodles and sauce. Toss over high heat until glossy. Finish with lime.'],
    []),

  R('chickpea-coconut-curry', 'Chickpea coconut curry', 30, 'easy', 3,
    ['chickpeas', 'coconut-milk', 'onion', 'garlic', 'curry-powder'], ['canned-tomatoes', 'spinach', 'ginger', 'rice', 'cilantro'],
    ['Soften the onion, then add garlic, ginger, and curry powder for 1 minute.',
     'Add chickpeas, coconut milk, and tomatoes if using.',
     'Simmer 15 minutes until slightly thickened.',
     'Stir in spinach to wilt and serve over rice with cilantro.'],
    ['vegan', 'one-pan']),

  R('easy-chicken-curry', 'Easy chicken curry', 40, 'medium', 4,
    ['chicken-thigh', 'onion', 'garlic', 'curry-powder', 'coconut-milk'], ['ginger', 'canned-tomatoes', 'rice', 'cilantro'],
    ['Brown bite-size chicken pieces and set aside.',
     'Soften the onion, then add garlic, ginger, and curry powder.',
     'Return the chicken with coconut milk and simmer 20 minutes.',
     'Serve over rice, topped with cilantro.'],
    ['comfort']),

  R('red-lentil-dal', 'Red lentil dal', 35, 'easy', 4,
    ['lentils', 'onion', 'garlic', 'turmeric', 'cumin'], ['ginger', 'coconut-milk', 'butter', 'rice', 'cilantro', 'chili-flakes'],
    ['Simmer rinsed lentils with turmeric in water until soft, about 20 minutes.',
     'Meanwhile fry onion, garlic, ginger, and cumin in oil or butter until golden.',
     'Stir the fried aromatics into the lentils and season well.',
     'Loosen with coconut milk if you have it. Serve with rice.'],
    ['vegan', 'comfort']),

  R('lentil-soup', 'Cozy lentil soup', 40, 'easy', 4,
    ['lentils', 'carrot', 'celery', 'onion', 'stock'], ['garlic', 'cumin', 'canned-tomatoes', 'lemon'],
    ['Soften diced onion, carrot, and celery in olive oil.',
     'Add garlic and cumin, then the lentils, stock, and tomatoes if using.',
     'Simmer 25 minutes until the lentils are tender.',
     'Brighten with lemon juice right before serving.'],
    ['vegan', 'soup']),

  R('sheet-pan-sausage', 'Sheet-pan sausage and veg', 40, 'easy', 2,
    ['sausage', 'potato', 'bell-pepper', 'onion'], ['broccoli', 'paprika', 'mustard', 'garlic'],
    ['Heat the oven to 220C / 425F.',
     'Chop potatoes small, toss everything with oil, salt, and paprika on one tray.',
     'Roast 20 minutes, flip, then roast 15 more until the sausages are browned.',
     'Serve with mustard.'],
    ['one-pan']),

  R('baked-salmon-potatoes', 'Baked salmon and potatoes', 35, 'easy', 2,
    ['salmon', 'potato', 'lemon', 'garlic'], ['butter', 'rosemary', 'broccoli', 'green-beans'],
    ['Roast halved baby potatoes with oil and rosemary at 200C / 400F for 20 minutes.',
     'Push the potatoes aside and add the salmon and greens to the tray.',
     'Top the salmon with garlic butter and lemon slices.',
     'Roast 12 more minutes until the salmon flakes.'],
    ['one-pan']),

  R('fish-tacos', 'Crispy fish tacos', 30, 'medium', 2,
    ['white-fish', 'tortillas', 'cabbage', 'lime', 'mayo'], ['flour', 'paprika', 'cilantro', 'sriracha', 'avocado'],
    ['Toss shredded cabbage with lime juice and salt to make a quick slaw.',
     'Stir mayo with lime and sriracha for the sauce.',
     'Dust fish pieces with flour and paprika, then pan-fry until golden.',
     'Build tacos: warm tortillas, slaw, fish, sauce, cilantro.'],
    []),

  R('garlic-butter-shrimp', 'Garlic butter shrimp', 15, 'easy', 2,
    ['shrimp', 'butter', 'garlic', 'lemon'], ['parsley', 'chili-flakes', 'pasta', 'rice', 'bread'],
    ['Pat the shrimp dry and season with salt.',
     'Melt butter with lots of sliced garlic and chili flakes.',
     'Add shrimp and cook 1 to 2 minutes per side until pink.',
     'Hit with lemon juice and parsley. Serve over pasta, rice, or with bread.'],
    ['quick']),

  R('honey-garlic-salmon', 'Honey garlic salmon', 20, 'easy', 2,
    ['salmon', 'honey', 'soy-sauce', 'garlic'], ['ginger', 'sesame-seeds', 'rice', 'broccoli', 'scallion'],
    ['Mix honey, soy sauce, and grated garlic into a glaze.',
     'Sear the salmon skin-side down in a hot pan, 4 minutes.',
     'Flip, pour in the glaze, and spoon it over as it bubbles.',
     'Serve over rice with steamed broccoli and sesame seeds.'],
    ['quick']),

  R('caprese-salad', 'Caprese salad', 10, 'easy', 2,
    ['tomato', 'mozzarella', 'basil'], ['vinegar', 'bread'],
    ['Slice tomatoes and mozzarella thick, and shingle them on a plate.',
     'Tuck basil leaves between the layers.',
     'Season with flaky salt and good olive oil, plus a drizzle of balsamic.',
     'Serve with bread to mop the plate.'],
    ['vegetarian', 'no-cook', 'quick']),

  R('greek-ish-salad', 'Greek-ish chopped salad', 15, 'easy', 2,
    ['cucumber', 'tomato', 'feta', 'olives'], ['onion', 'lettuce', 'lemon', 'oregano', 'bell-pepper'],
    ['Chop cucumber, tomato, and pepper into big chunks. Slice the onion thin.',
     'Dress with olive oil, lemon juice, oregano, salt, and pepper.',
     'Top with a slab of feta and the olives.',
     'Let it sit 5 minutes before eating so the juices mingle.'],
    ['vegetarian', 'no-cook', 'quick']),

  R('chickpea-salad-sandwich', 'Smashed chickpea sandwich', 10, 'easy', 2,
    ['chickpeas', 'mayo', 'lemon', 'bread'], ['celery', 'onion', 'mustard', 'lettuce'],
    ['Drain the chickpeas and smash them roughly with a fork.',
     'Mix with mayo, lemon juice, mustard, and diced celery or onion.',
     'Season boldly with salt and pepper.',
     'Pile onto bread with lettuce.'],
    ['vegetarian', 'no-cook', 'quick']),

  R('crispy-tofu-stir-fry', 'Crispy tofu stir-fry', 25, 'medium', 2,
    ['tofu', 'soy-sauce', 'garlic', 'broccoli'], ['ginger', 'sesame-oil', 'rice', 'sriracha', 'scallion', 'honey'],
    ['Press the tofu, cube it, and pat very dry.',
     'Pan-fry in hot oil without moving it until golden on two sides.',
     'Add broccoli and a splash of water. Cover 2 minutes to steam.',
     'Add garlic, then soy sauce and honey. Toss until sticky. Serve over rice.'],
    ['vegan']),

  R('miso-soup', 'Miso soup', 15, 'easy', 2,
    ['miso', 'tofu', 'scallion'], ['mushrooms', 'spinach'],
    ['Bring water to a bare simmer with mushrooms if using.',
     'Add cubed tofu and spinach for the last 2 minutes.',
     'Turn off the heat, then whisk in the miso through a strainer or with a fork.',
     'Never boil after the miso goes in. Top with scallions.'],
    ['vegan', 'quick', 'soup']),

  R('breakfast-hash', 'Breakfast potato hash', 30, 'medium', 2,
    ['potato', 'onion', 'bell-pepper', 'eggs'], ['bacon', 'paprika', 'cheddar', 'scallion'],
    ['Dice the potatoes small and fry in a generous slick of oil until crisp, about 15 minutes.',
     'Add onion, pepper, and bacon if using. Cook 5 more minutes.',
     'Season with paprika, then make wells and crack in the eggs.',
     'Cover until the whites set. Top with cheese and scallions.'],
    ['one-pan', 'breakfast']),

  R('loaded-baked-potato', 'Loaded baked potato', 15, 'easy', 1,
    ['potato', 'butter', 'cheddar'], ['sour-cream', 'bacon', 'scallion', 'broccoli'],
    ['Stab the potato all over and microwave 10 to 12 minutes until soft.',
     'Split it open and fluff the inside with a fork.',
     'Load with butter, cheese, and crispy bacon.',
     'Finish with sour cream and scallions.'],
    ['vegetarian', 'quick', 'comfort']),

  R('zucchini-fritters', 'Zucchini fritters', 30, 'medium', 2,
    ['zucchini', 'eggs', 'flour'], ['feta', 'scallion', 'garlic', 'sour-cream', 'lemon'],
    ['Grate the zucchini, salt it, and squeeze out as much water as you can. This is the whole trick.',
     'Mix with egg, flour, feta, and scallions into a thick batter.',
     'Fry spoonfuls in hot oil, flattening slightly, until golden on both sides.',
     'Serve with sour cream and lemon.'],
    ['vegetarian']),

  R('bacon-cabbage', 'Bacon and cabbage stir-fry', 20, 'easy', 2,
    ['cabbage', 'bacon', 'garlic'], ['soy-sauce', 'chili-flakes', 'rice'],
    ['Crisp chopped bacon in a wide pan and set it aside, keeping the fat.',
     'Stir-fry roughly torn cabbage in the fat over high heat until charred at the edges.',
     'Add garlic and chili flakes for the last minute.',
     'Return the bacon with a splash of soy sauce. Serve with rice.'],
    ['quick']),

  R('smashed-cucumber-salad', 'Smashed cucumber salad', 10, 'easy', 2,
    ['cucumber', 'garlic', 'rice-vinegar', 'sesame-oil'], ['chili-flakes', 'soy-sauce', 'sesame-seeds'],
    ['Whack the cucumbers with a rolling pin until they crack, then tear into chunks.',
     'Salt them for 5 minutes, then pour off the water.',
     'Dress with grated garlic, rice vinegar, sesame oil, and soy sauce.',
     'Top with chili flakes and sesame seeds. Serve cold.'],
    ['vegan', 'no-cook', 'quick']),

  R('gochujang-chicken', 'Gochujang glazed chicken', 30, 'medium', 2,
    ['chicken-thigh', 'gochujang', 'soy-sauce', 'garlic', 'honey'], ['ginger', 'sesame-seeds', 'rice', 'scallion'],
    ['Whisk gochujang, soy sauce, honey, garlic, and a splash of water.',
     'Sear the chicken until golden on both sides.',
     'Pour in the glaze and simmer, turning, until sticky and lacquered.',
     'Serve over rice with scallions and sesame seeds.'],
    ['spicy']),

  R('chicken-congee', 'Chicken congee', 60, 'easy', 3,
    ['rice', 'chicken-thigh', 'ginger', 'stock'], ['scallion', 'sesame-oil', 'soy-sauce', 'eggs'],
    ['Rinse the rice, then simmer it with stock, water, ginger slices, and the chicken.',
     'Cook low and slow about 45 minutes, stirring now and then, until porridgy.',
     'Shred the chicken and stir it back in. Season with salt.',
     'Top bowls with scallions, sesame oil, and soy sauce.'],
    ['comfort', 'soup']),

  R('mug-cookie', 'Chocolate chip mug cookie', 5, 'easy', 1,
    ['flour', 'butter', 'chocolate-chips'], ['milk'],
    ['Melt a tablespoon of butter in a mug.',
     'Stir in a spoon of sugar, a pinch of salt, and a splash of milk.',
     'Mix in 3 spoons of flour and a handful of chocolate chips.',
     'Microwave 40 to 60 seconds. It should look slightly underdone. Eat warm.'],
    ['vegetarian', 'quick', 'dessert']),

  R('pb-banana-toast', 'Peanut butter banana toast', 5, 'easy', 1,
    ['bread', 'peanut-butter', 'banana'], ['honey', 'cinnamon'],
    ['Toast the bread until golden.',
     'Spread generously with peanut butter while hot.',
     'Top with banana coins.',
     'Drizzle with honey and dust with cinnamon.'],
    ['vegetarian', 'no-cook', 'quick', 'breakfast']),

  R('garlic-butter-rice', 'Garlic butter rice', 25, 'easy', 3,
    ['rice', 'butter', 'garlic'], ['stock', 'parsley', 'parmesan'],
    ['Sizzle sliced garlic in butter until pale gold, not brown.',
     'Stir in the rinsed rice to coat every grain.',
     'Add stock or water and cook, covered, on low for 15 minutes.',
     'Rest 5 minutes, then fluff with parsley or parmesan.'],
    ['vegetarian']),

  R('roast-veg-couscous', 'Roast veg couscous bowl', 35, 'easy', 2,
    ['couscous', 'zucchini', 'bell-pepper', 'onion'], ['feta', 'lemon', 'chickpeas', 'cumin', 'parsley'],
    ['Roast chunked zucchini, pepper, and onion with oil and cumin at 220C / 425F for 25 minutes.',
     'Pour boiling water over the couscous, cover 5 minutes, and fluff.',
     'Toss the veg and chickpeas through the couscous.',
     'Finish with lemon juice, feta, and parsley.'],
    ['vegetarian']),
];
