// Per-recipe cooking amounts + energy estimates.
// `amounts` covers the required ingredients (whole-recipe quantities, see
// each recipe's servings); optional ingredients are to taste.
// `kcal` is an estimate PER SERVING for the required ingredients cooked
// as written, rounded to the nearest 10.
export const NUTRITION = {
  'garlic-butter-pasta':    { kcal: 640, amounts: { pasta: '200 g', butter: '40 g', garlic: '3 cloves', parmesan: '40 g' } },
  'aglio-e-olio':           { kcal: 520, amounts: { pasta: '200 g', garlic: '4 cloves', 'chili-flakes': '1 tsp' } },
  'weeknight-tomato-pasta': { kcal: 480, amounts: { pasta: '300 g', 'canned-tomatoes': '400 g', garlic: '3 cloves', onion: '1 (150 g)' } },
  'creamy-mushroom-pasta':  { kcal: 660, amounts: { pasta: '200 g', mushrooms: '250 g', garlic: '2 cloves', 'heavy-cream': '150 ml' } },
  'tuna-lemon-pasta':       { kcal: 560, amounts: { pasta: '200 g', 'canned-tuna': '145 g tin', garlic: '2 cloves', lemon: '1' } },
  'bacon-egg-pasta':        { kcal: 700, amounts: { pasta: '200 g', bacon: '100 g', eggs: '2 + 1 yolk', parmesan: '50 g' } },
  'stovetop-mac':           { kcal: 680, amounts: { pasta: '200 g', milk: '250 ml', butter: '25 g', cheddar: '150 g' } },
  'egg-fried-rice':         { kcal: 470, amounts: { rice: '350 g cooked', eggs: '3', scallion: '3 stalks', 'soy-sauce': '2 tbsp' } },
  'kimchi-fried-rice':      { kcal: 500, amounts: { rice: '350 g cooked', kimchi: '150 g', eggs: '2' } },
  'chicken-fried-rice':     { kcal: 550, amounts: { rice: '350 g cooked', 'chicken-breast': '200 g', eggs: '2', 'soy-sauce': '2 tbsp' } },
  'one-pot-chicken-rice':   { kcal: 620, amounts: { 'chicken-thigh': '600 g', rice: '300 g', onion: '1 (150 g)', garlic: '3 cloves', stock: '600 ml' } },
  'honey-soy-chicken':      { kcal: 480, amounts: { 'chicken-thigh': '400 g', 'soy-sauce': '3 tbsp', honey: '2 tbsp', garlic: '3 cloves' } },
  'chicken-stir-fry':       { kcal: 380, amounts: { 'chicken-breast': '300 g', 'bell-pepper': '1 (150 g)', broccoli: '200 g', 'soy-sauce': '2 tbsp', garlic: '2 cloves' } },
  'beef-and-broccoli':      { kcal: 460, amounts: { steak: '300 g', broccoli: '300 g', 'soy-sauce': '3 tbsp', garlic: '3 cloves', ginger: '15 g' } },
  'beef-tacos':             { kcal: 560, amounts: { 'ground-beef': '500 g', tortillas: '9 small', onion: '1 (150 g)', cumin: '2 tsp', paprika: '2 tsp' } },
  'cheese-quesadillas':     { kcal: 520, amounts: { tortillas: '4 large', cheddar: '160 g' } },
  'burrito-bowl':           { kcal: 590, amounts: { rice: '160 g', 'black-beans': '240 g drained', corn: '150 g', lime: '1' } },
  'weeknight-chili':        { kcal: 520, amounts: { 'ground-beef': '500 g', 'canned-tomatoes': '400 g', 'black-beans': '240 g drained', onion: '1 (150 g)', cumin: '1 tbsp' } },
  'simple-bolognese':       { kcal: 640, amounts: { 'ground-beef': '500 g', 'canned-tomatoes': '400 g', onion: '1 (150 g)', garlic: '3 cloves', pasta: '400 g' } },
  'cheesy-omelette':        { kcal: 480, amounts: { eggs: '3', butter: '15 g', cheddar: '50 g' } },
  'scrambled-egg-toast':    { kcal: 430, amounts: { eggs: '2', bread: '2 slices', butter: '15 g' } },
  'shakshuka':              { kcal: 340, amounts: { eggs: '4', 'canned-tomatoes': '400 g', onion: '1 (150 g)', 'bell-pepper': '1 (150 g)', cumin: '1 tsp' } },
  'egg-drop-soup':          { kcal: 140, amounts: { stock: '750 ml', eggs: '2', scallion: '2 stalks' } },
  'fluffy-pancakes':        { kcal: 420, amounts: { flour: '250 g', eggs: '2', milk: '300 ml', 'baking-powder': '2 tsp' } },
  'french-toast':           { kcal: 450, amounts: { bread: '4 thick slices', eggs: '2', milk: '100 ml', cinnamon: '1 tsp' } },
  'banana-oat-pancakes':    { kcal: 360, amounts: { banana: '2 (240 g)', oats: '100 g', eggs: '2' } },
  'overnight-oats':         { kcal: 390, amounts: { oats: '60 g', milk: '150 ml', honey: '1 tbsp' } },
  'yogurt-parfait':         { kcal: 340, amounts: { 'greek-yogurt': '200 g', granola: '50 g', berries: '100 g' } },
  'grilled-cheese':         { kcal: 540, amounts: { bread: '2 slices', butter: '20 g', cheddar: '80 g' } },
  'tomato-soup':            { kcal: 180, amounts: { 'canned-tomatoes': '800 g', onion: '1 (150 g)', garlic: '3 cloves', stock: '500 ml' } },
  'avocado-toast':          { kcal: 380, amounts: { bread: '2 slices', avocado: '1 (150 g)', lemon: 'half' } },
  'blt':                    { kcal: 550, amounts: { bread: '2 slices', bacon: '80 g', lettuce: '2 leaves', tomato: '1 (120 g)', mayo: '1 tbsp' } },
  'tuna-melt':              { kcal: 560, amounts: { bread: '2 slices', 'canned-tuna': '145 g tin', mayo: '2 tbsp', cheddar: '60 g' } },
  'chicken-noodle-soup':    { kcal: 320, amounts: { 'chicken-breast': '300 g', stock: '1.5 l', carrot: '2 (150 g)', celery: '2 sticks', pasta: '150 g' } },
  'upgraded-ramen':         { kcal: 540, amounts: { 'instant-noodles': '1 packet', eggs: '1', scallion: '2 stalks' } },
  'peanut-noodles':         { kcal: 620, amounts: { pasta: '200 g', 'peanut-butter': '60 g', 'soy-sauce': '2 tbsp', garlic: '1 clove' } },
  'pad-thai-ish':           { kcal: 520, amounts: { 'rice-noodles': '160 g', eggs: '2', 'fish-sauce': '2 tbsp', lime: '1' } },
  'chickpea-coconut-curry': { kcal: 470, amounts: { chickpeas: '480 g drained', 'coconut-milk': '400 ml', onion: '1 (150 g)', garlic: '3 cloves', 'curry-powder': '1 tbsp' } },
  'easy-chicken-curry':     { kcal: 560, amounts: { 'chicken-thigh': '600 g', onion: '2 (300 g)', garlic: '4 cloves', 'curry-powder': '1.5 tbsp', 'coconut-milk': '400 ml' } },
  'red-lentil-dal':         { kcal: 320, amounts: { lentils: '300 g', onion: '1 (150 g)', garlic: '3 cloves', turmeric: '1 tsp', cumin: '1.5 tsp' } },
  'lentil-soup':            { kcal: 300, amounts: { lentils: '250 g', carrot: '2 (150 g)', celery: '2 sticks', onion: '1 (150 g)', stock: '1.2 l' } },
  'sheet-pan-sausage':      { kcal: 680, amounts: { sausage: '300 g', potato: '400 g', 'bell-pepper': '1 (150 g)', onion: '1 (150 g)' } },
  'baked-salmon-potatoes':  { kcal: 560, amounts: { salmon: '2 fillets (250 g)', potato: '400 g', lemon: '1', garlic: '2 cloves' } },
  'fish-tacos':             { kcal: 540, amounts: { 'white-fish': '300 g', tortillas: '6 small', cabbage: '150 g', lime: '2', mayo: '3 tbsp' } },
  'garlic-butter-shrimp':   { kcal: 300, amounts: { shrimp: '300 g', butter: '40 g', garlic: '4 cloves', lemon: '1' } },
  'honey-garlic-salmon':    { kcal: 450, amounts: { salmon: '2 fillets (250 g)', honey: '2 tbsp', 'soy-sauce': '2 tbsp', garlic: '3 cloves' } },
  'caprese-salad':          { kcal: 330, amounts: { tomato: '2 large (300 g)', mozzarella: '125 g ball', basil: 'a handful' } },
  'greek-ish-salad':        { kcal: 280, amounts: { cucumber: '1 (300 g)', tomato: '2 (240 g)', feta: '100 g', olives: '60 g' } },
  'chickpea-salad-sandwich':{ kcal: 460, amounts: { chickpeas: '240 g drained', mayo: '2 tbsp', lemon: 'half', bread: '4 slices' } },
  'crispy-tofu-stir-fry':   { kcal: 350, amounts: { tofu: '350 g firm', 'soy-sauce': '2 tbsp', garlic: '3 cloves', broccoli: '250 g' } },
  'miso-soup':              { kcal: 120, amounts: { miso: '2 tbsp', tofu: '150 g silken', scallion: '2 stalks' } },
  'breakfast-hash':         { kcal: 430, amounts: { potato: '400 g', onion: '1 (150 g)', 'bell-pepper': '1 (150 g)', eggs: '2' } },
  'loaded-baked-potato':    { kcal: 520, amounts: { potato: '1 large (300 g)', butter: '20 g', cheddar: '60 g' } },
  'zucchini-fritters':      { kcal: 280, amounts: { zucchini: '2 (400 g)', eggs: '1', flour: '60 g' } },
  'bacon-cabbage':          { kcal: 340, amounts: { cabbage: 'half a head (400 g)', bacon: '120 g', garlic: '3 cloves' } },
  'smashed-cucumber-salad': { kcal: 90,  amounts: { cucumber: '2 (500 g)', garlic: '2 cloves', 'rice-vinegar': '2 tbsp', 'sesame-oil': '1 tbsp' } },
  'gochujang-chicken':      { kcal: 520, amounts: { 'chicken-thigh': '400 g', gochujang: '2 tbsp', 'soy-sauce': '1 tbsp', garlic: '3 cloves', honey: '1 tbsp' } },
  'chicken-congee':         { kcal: 380, amounts: { rice: '150 g', 'chicken-thigh': '300 g', ginger: '20 g', stock: '1 l (plus 500 ml water)' } },
  'mug-cookie':             { kcal: 420, amounts: { flour: '3 tbsp', butter: '1 tbsp', 'chocolate-chips': '20 g' } },
  'pb-banana-toast':        { kcal: 420, amounts: { bread: '2 slices', 'peanut-butter': '30 g', banana: '1 (120 g)' } },
  'garlic-butter-rice':     { kcal: 380, amounts: { rice: '300 g', butter: '40 g', garlic: '4 cloves' } },
  'roast-veg-couscous':     { kcal: 420, amounts: { couscous: '160 g', zucchini: '1 (200 g)', 'bell-pepper': '1 (150 g)', onion: '1 (150 g)' } },
};
